### PR TITLE
Initial Travis CI build config and badge

### PR DESCRIPTION
**Pull request by atz**

### CODE REVIEW

**Comment by dazza-codes** [comment]
This targets scala `2.12.3` but the latest recommended scala for Kafka 0.11.x is scala `2.11`.  So, I don't know if this version consistency with deploying the same scala version is a problem, just saying that I'm not looking at deploying scala `2.12.x` until the services we need are using it in their stable releases (LMK if they are using it already and we should be deploying it).

**Comment by dazza-codes** [comment]
What does travis.ci recommend WRT caching the build dependencies that are downloade by sbt?  In maven, I've used a travis cache on the `~/.m2` directory before (or subdirectories of it, like just the repository).  Can we do this with `sbt` and, if so, why not do it here?

**Comment by atz** [comment]
@darrenleeweber Yeah, I am willing to entertain caching strategies subsequently, mostly for `banana-rdf` if we are stuck compiling it from source (since it isn't published for 2.11.x).  But right now the execution time is only around 3 minutes, so I think caching optimization can be deferred.  

We can test a range of scala versions, if desired.  I was curious to see if 2.12 worked, given the banana-rdf limitation.  Specifying the scala version also solved build errors, as you can see from the 2-commit history here.

**Comment by atz** [comment]
Merged in @Maatary's patch to test `2.11.11` also.

**Pull request merged**
